CREATE TABLE IF NOT EXISTS `status` (
    `id_status` INT PRIMARY KEY AUTO_INCREMENT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    `name` VARCHAR(255) NOT NULL UNIQUE
);